name: Build Binary

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  binary:
    permissions:
      contents: write
      pull-requests: write
    uses: langchain-ai/langsmith-plugin-binary/.github/workflows/build-binary.yml@10d9b1acab7cd4fbbca96475e8374192b9a93323 # v0.2.1
    secrets: inherit
    with:
      beta-branch: beta-0.2.0
      binary-directory: plugins/tracing/binary
