name: Build Binary

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  binary:
    permissions:
      contents: write
    uses: langchain-ai/langsmith-plugin-binary/.github/workflows/build-binary.yml@2385c00f91ee4603c304ea99b590d9a2ab073e1b # v0.2.0
    secrets: inherit
